### ISSUE TITLE
Add organization / delegation support

### ISSUE THREAD

**Issue by smortex** [puppetlabs/forge_issues#10]
## Use Case
As a member of a team owning a bunch of modules,
I want each member of that team to manage these modules **without sharing a common password across team members**.

## Describe the Solution You Would Like
From his user account, a user would create a new team, then invite other forge users to be part of that team.
Modules could be owned by a user of by a team.

## Describe Alternatives You've Considered
Sharing a password with a few person is not great (I do this for a small org), but for large organizations it is a no go.  In this case, automation help: users have no access to the forge, and only CI can operate the forge account through API.  This is what VoxPupuli does.

## Additional Context
n/a

**Comment by Ramesh7** [comment]
Thank you, @smortex, for the suggestion. I empathise with the challenges of publishing a module for a user when you have multiple contributors. The good news is that we have a similar plan in progress that should simplify the contributor experience. Stay tuned..!!!

**Comment by skarwaperforce** [comment]
This functionality was released as part of the organization launch in July 2024. Closing this issue. Thanks @smortex for the feedback and thoughts here
