### ISSUE TITLE
Do not fail if a module is not present on the forge

### ISSUE THREAD

**Issue by smortex** [puppetlabs/forge_issues#12]
## Use Case
We have some "low value modules" that we do not think are worth storing on the Puppet Forge.  When uploading a Puppetfile with such a module, the import fail because the module is not found and **no modules are imported at all**.

## Describe the Solution You Would Like
Instead of failing, the import should just produce a warning about the unknown module but proceed with all known ones, so that known modules can be tracked.

## Describe Alternatives You've Considered
Removing the offending modules should help, but who has time for that :smile: 

## Additional Context

Screenshot of the error preventing the import:

![Screenshot of the error](https://github.com/puppetlabs/forge_issues/assets/148721/b1e1fb27-c95a-4757-8622-f910507d8a7c)

**Comment by Ramesh7** [comment]
Thank you, @smortex , We will review internally and priorities the same.

**Comment by Ramesh7** [comment]
HI @smortex, wanted to let you know that we have implemented the enhancements, and they have been rolled out today. Please try them out and share your experience.

Thanks again for raising the issue and helping us improve Forge.

**Comment by smortex** [comment]
Awesome!  Works as expected, thanks!
