### ISSUE TITLE
reanimate/un-deprecate voxpupuli/puppet-windows_power

### ISSUE THREAD

**Issue by Lightning-** [puppetlabs/forge_issues#18]
URLs:
- https://forge.puppet.com/modules/puppet/windows_power/
- https://github.com/voxpupuli/puppet-windows_power

this module was deprecated/dropped by the original author years ago but we recently took over and brought it back to a new life

plz set the module back to an active state to allow us to push the recent/new release to forge was well :)

**Comment by skarwaperforce** [comment]
@Lightning- thanks for the request

Checking with @binford2k if there's anything that he feels needs to be checked here?

**Comment by binford2k** [comment]
@skarwaperforce tbh, conversation about this module is why I filed PF-3325

**Comment by Lightning-** [comment]
hum ... did i blow something up here? :thinking:

**Comment by skarwaperforce** [comment]
Hi @Lightning- we are picking this up soon, will update you in a couple of days

**Comment by Ramesh7** [comment]
Hi @Lightning-, have updated module and brought back to active. 

Closing the same, please feel free to reopen if things doesn't looks as expected. Thanks
