### ISSUE TITLE
Deprecate the jamesmcdonald/cpanm module

### ISSUE THREAD

**Issue by h-haaks** [puppetlabs/forge_issues#2]
The cpanm module has been transferred to voxpupuli.
Could you please mark https://forge.puppetlabs.com/modules/jamesmcdonald/cpanm as deprecated and link to https://forge.puppetlabs.com/modules/puppet/cpanm ?

**Comment by Ramesh7** [comment]
Deprecated https://forge.puppetlabs.com/modules/jamesmcdonald/cpanm/readme against https://forge.puppetlabs.com/modules/puppet/cpanm/readme, hence closing the same.
