### ISSUE TITLE
[Deprecate]: icinga/icinga -> puppet/icinga

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#20]
### Deprecated module

https://forge.puppet.com/modules/icinga/icinga/

### Replacement module

https://forge.puppet.com/modules/puppet/icinga

### What authority do you have for making this request?

I am a Vox Pupuli PMC member

### More information

Hi,
the repo got migrated from the previous owner and released under the vox pupuli namespace.

**Comment by Ramesh7** [comment]
icinga-icinga has been marked as deprecated in favor of puppet-icinga
