### ISSUE TITLE
[Deprecate|Transfer]: buzzdeee/memcached -> saz/memcached

### ISSUE THREAD

**Issue by buzzdeee** [puppetlabs/forge_issues#22]
### Deprecated module

https://forge.puppet.com/modules/buzzdeee/memcached

### Replacement module

https://forge.puppet.com/modules/saz/memcached

### What authority do you have for making this request?

It's my module. (github username matches repo owner or contact info provided for verification)

### More information

My buzzdeee-memcached module only supported OpenBSD.

OpenBSD support to saz-memcached was added here: https://github.com/saz/puppet-memcached/pull/162
It's now an easy drop-in replacement for my module.

My buzzdeee-memcached module is now marked as deprecated on GitHub: https://github.com/buzzdeee/buzzdeee-memcached

Would like to have my Forge Module deprecated as well, pointing to saz-memcached as replacement.

**Comment by Ramesh7** [comment]
buzzdeee-memcached has been marked as deprecated in favor of saz-memcached!
