### ISSUE TITLE
[Bug]: Autogenerated DSC module xactivedirectory reporting incorrectly

### ISSUE THREAD

**Issue by andytroup** [puppetlabs/forge_issues#24]
### What happened?

The module is version 3.0.0-0-1 in the uploaded puppetfile, but the changelog information is reporting changes prior to this version

![image](https://github.com/puppetlabs/forge_issues/assets/57898050/dfaffcc3-61a3-45ea-91a0-d175c1ecb858)

### What browsers / clients are you seeing the problem on?

Chrome

**Comment by skarwaperforce** [comment]
As discussed with @andytroup, the release showcased in the screenshot (2.10.0.0.3) came in later as compared to 3.0.0.0.1. Hence closing this is this isn't a bug
