### ISSUE TITLE
[Deprecate]: icinga/icinga2 

### ISSUE THREAD

**Issue by lbetz** [puppetlabs/forge_issues#26]
### Deprecated module

https://forge.puppet.com/modules/icinga/icinga2

### Replacement module

https://forge.puppet.com/modules/puppet/icinga2

### What authority do you have for making this request?

The repository has already been transferred

**Comment by Ramesh7** [comment]
[icinga-icinga2](https://forge.puppet.com/modules/icinga/icinga2) has been marked as deprecated in favor of [puppet-icinga2](https://forge.puppet.com/modules/puppet/icinga2)
