### ISSUE TITLE
[Deprecate]: icinga/icingadb

### ISSUE THREAD

**Issue by lbetz** [puppetlabs/forge_issues#27]
### Deprecated module

https://forge.puppet.com/modules/icinga/icingadb

### Replacement module

https://forge.puppet.com/modules/voxpupuli/icingadb

### What authority do you have for making this request?

The repository has already been transferred

**Comment by Ramesh7** [comment]
[icinga-icingadb](https://forge.puppet.com/modules/icinga/icingadb) has been marked as deprecated in favor of [puppet-icingadb](https://forge.puppet.com/modules/puppet/icingadb)
