### ISSUE TITLE
[Deprecate]: icinga/icingaweb2 

### ISSUE THREAD

**Issue by lbetz** [puppetlabs/forge_issues#28]
### Deprecated module

https://forge.puppet.com/modules/icinga/icingaweb2

### Replacement module

https://forge.puppet.com/modules/puppet/icingaweb2

### What authority do you have for making this request?

The repository has already been transferred

**Comment by Ramesh7** [comment]
[icinga-icingaweb2](https://forge.puppet.com/modules/icinga/icingaweb2) has been marked as deprecated in favor of [puppet-icingaweb2](https://forge.puppet.com/modules/puppet/icingaweb2)
