### ISSUE TITLE
Provide a github issue template for module deprecations

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#3]
## Use Case

Hi,
at Vox Pupuli people often migrate modules to us that were previously released under a different forge namespace. As far as I know people need to raise an issue on this board and ask to deprecate the old module and migrate the `approved` badge. I think it would be helpful for newcomers if you could offer a github issue template for this process.

## Describe the Solution You Would Like

An easy to use github issue template

**Comment by binford2k** [comment]
Try out the new templates and offer suggestions for improvement if you'd like. https://github.com/puppetlabs/forge_issues/issues/new/choose
