### ISSUE TITLE
Transfer: pcfens-ca_cert 

### ISSUE THREAD

**Issue by h-haaks** [puppetlabs/forge_issues#31]
### Deprecated module

https://forge.puppetlabs.com/modules/pcfens/ca_cert/readme

### Replacement module

https://forge.puppetlabs.com/modules/puppet/ca_cert/readme

### What authority do you have for making this request?

The repository has already been transferred

**Comment by skarwaperforce** [comment]
@binford2k can you approve this?

**Comment by Ramesh7** [comment]
pcfens-ca_cert has been marked as deprecated in favor of puppet-ca_cert!
