### ISSUE TITLE
[Deprecate]: please check camptocamp/openssl

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#34]
### Deprecated module

camptocamp/openssl

### Replacement module

puppet/openssl

### What authority do you have for making this request?

It's my module. (github username matches repo owner or contact info provided for verification), I am a Vox Pupuli PMC member, The repository has already been transferred

### More information

Hi,
https://forge.puppet.com/modules/camptocamp/openssl/readme has been transferred to https://forge.puppet.com/modules/puppet/openssl/readme. The old one is already deprecated but doesn't point to the new module. Can you update that please?

**Comment by Ramesh7** [comment]
camptocamp-openssl has been marked as deprecated in favor of puppet-openssl!

Hence closing the same.
