### ISSUE TITLE
[Deprecate]:  Please deprecate multiple modules

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#35]
### Deprecated module

puppet-dropbear

### What authority do you have for making this request?

It's my module. (github username matches repo owner or contact info provided for verification), I am a Vox Pupuli PMC member

### More information

Hi, 
Vox Pupuli deprecated multiple modules. The GitHub repos are already archived. Can you please deprecate them on the forge:

* puppet-dropbear
* puppet-etherpad
* puppet-ghost
* puppet-jenkins_job_builder
* puppet-pxe

**Comment by rajat-puppet** [comment]
@bastelfreak All the listed modules have been deprecated, please verify.

**Comment by bastelfreak** [comment]
thanks, looks good!
