### ISSUE TITLE
[Deprecate|Transfer]: github_action_runners

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#36]
### Deprecated module

https://forge.puppet.com/modules/telefonica/github_actions_runner

### Replacement module

https://forge.puppet.com/modules/puppet/github_actions_runner/readme

### What authority do you have for making this request?

It's my module. (github username matches repo owner or contact info provided for verification), I am a Vox Pupuli PMC member

### More information

Hi,
Telefonica archived their original repository: https://github.com/Telefonica/puppet-github-actions-runner

Vox Pupuli forked it and maintains it now. Please deprecate the old module.

**Comment by rajat-puppet** [comment]
@bastelfreak This has been done. Please verify.

**Comment by bastelfreak** [comment]
thanks a lot!
