### ISSUE TITLE
[Deprecate]: https://forge.puppet.com/modules/puppet/report_hipchat/readme

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#38]
### Deprecated module

https://forge.puppet.com/modules/puppet/report_hipchat/readme

### What authority do you have for making this request?

It's my module. (github username matches repo owner or contact info provided for verification), I am a Vox Pupuli PMC member

### More information

Hi, please deprecate the module, we archived the git repository.

**Comment by rajat-puppet** [comment]
@bastelfreak Can you confirm if this request has been catered?

**Comment by bastelfreak** [comment]
yes, thanks!
