### ISSUE TITLE
[Deprecate]: https://forge.puppet.com/modules/puppet/mcollective/

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#39]
### Deprecated module

https://forge.puppet.com/modules/puppet/mcollective

### Replacement module

https://forge.puppet.com/modules/choria/choria/readme

### What authority do you have for making this request?

It's my module. (github username matches repo owner or contact info provided for verification), I am a Vox Pupuli PMC member

### More information

Hi,
we're going to archive the git repo, please deprecate the module and suggest https://forge.puppet.com/modules/choria/choria/readme as the successor.

**Comment by rajat-puppet** [comment]
@bastelfreak Can you confirm if this request has been catered?

**Comment by bastelfreak** [comment]
looks good, thanks!
