### ISSUE TITLE
Migrate module from rtyler/jenkins to puppet/jenkins

### ISSUE THREAD

**Issue by ekohl** [puppetlabs/forge_issues#4]
This comes from https://github.com/voxpupuli/puppet-jenkins/issues/1089. 

https://forge.puppet.com/modules/rtyler/jenkins has been migrated to https://github.com/jenkinsci/puppet-jenkins which has since transferred to https://github.com/voxpupuli/puppet-jenkins.

https://forge.puppet.com/modules/rtyler/jenkins is still an approved module, but without a release since 2016. I don't think there ever was a release form the Jenkins namespace.

I'd like to deprecate https://forge.puppet.com/modules/rtyler/jenkins and recommend migration to https://forge.puppetlabs.com/modules/puppet/jenkins. I'm neutral about moving the approval, but obviously the approval should be removed from the deprecated module.

**Comment by Ramesh7** [comment]
Deprecated https://forge.puppet.com/modules/rtyler/jenkins against https://forge.puppetlabs.com/modules/puppet/jenkins, hence closing the same.
