### ISSUE TITLE
[Deprecate|]: https://forge.puppet.com/modules/puppet/download_file

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#40]
### Deprecated module

https://forge.puppet.com/modules/puppet/download_file

### Replacement module

https://forge.puppet.com/modules/puppet/archive

### What authority do you have for making this request?

It's my module. (github username matches repo owner or contact info provided for verification), I am a Vox Pupuli PMC member

### More information

Hi,
we don't maintain https://forge.puppet.com/modules/puppet/download_file anymore. Can you please deprecate it and suggest https://forge.puppet.com/modules/puppet/archive as the successor?

**Comment by praj1001** [comment]
@bastelfreak, done.
