### ISSUE TITLE
[Transfer]: biemond/wildfly

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#41]
### Deprecated module

https://forge.puppet.com/modules/biemond/wildfly/readme

### Replacement module

https://forge.puppet.com/modules/puppet/wildfly/readme

### What authority do you have for making this request?

It's my module. (github username matches repo owner or contact info provided for verification), I am a Vox Pupuli PMC member, The repository has already been transferred

### More information

Hi,
some time ago the wildfly module was transferred to us. Can you please archive the old module on the forge and transfer the `approved` badge?

**Comment by praj1001** [comment]
@bastelfreak , done.
