### ISSUE TITLE
[Deprecate]: puppet/visualstudio

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#43]
### Deprecated module

https://forge.puppetlabs.com/modules/puppet/visualstudio/readme

### What authority do you have for making this request?

It's my module. (github username matches repo owner or contact info provided for verification), I am a Vox Pupuli PMC member

### More information

Hi,
The module isn't maintained anymore and we archived the git repo. Please deprecate it on the forge.

**Comment by praj1001** [comment]
@bastelfreak , It has been marked as deprecated now.
