### ISSUE TITLE
Deprecate dobbymoodge/posix_acl

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#5]
## Use Case

Hi,
Please deprecate:
* https://forge.puppet.com/modules/dobbymoodge/posix_acl

It was migrated a long time ago to:

* https://forge.puppet.com/modules/puppet/posix_acl/

**Comment by Ramesh7** [comment]
Deprecated https://forge.puppet.com/modules/dobbymoodge/posix_acl/readme against https://forge.puppet.com/modules/puppet/posix_acl/readme, hence closing the same.
