### ISSUE TITLE
Deprecate ccooke-collections in favour of voxpupuli-collections

### ISSUE THREAD

**Issue by ccooke** [puppetlabs/forge_issues#6]
Hi. I have migrated my collections module to Vox Pupuli - could you please deprecate the original version?

**Comment by Ramesh7** [comment]
Looks like there is typo with owner as Vox has `puppet` usename on Forge, i belive it should be `puppet-collections`.

Have deprecated https://forge.puppet.com/modules/ccooke/collections/readme against https://forge.puppet.com/modules/puppet/collections/readme, hence closing the same.
