### ISSUE TITLE
Deprecate trlinkin/nsswitch

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/forge_issues#7]
## Use Case

Hi, https://forge.puppet.com/modules/trlinkin/nsswitch/readme isn't maintained anymore. Please deprecate it and move the approved badge to https://forge.puppet.com/modules/puppet/nsswitch/readme.

**Comment by Ramesh7** [comment]
Deprecated https://forge.puppet.com/modules/trlinkin/nsswitch/readme against https://forge.puppet.com/modules/puppet/nsswitch/readme and added `approved` badge.
Hence closing the same.
